In [25]:
import pandas as pd
import numpy as np
import joblib
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv(r"E:\salary prediction\data\salary_prediction_data.csv")
df

job_experience_years  previous_salary  study_hours_per_day  python_skill  \
0                      0            10000                    2             3   
1                      1            12000                    3             4   
2                      2            15000                    4             5   
3                      3            18000                    5             6   
4                      4            20000                    6             7   
5                      5            22000                    7             8   
6                      6            25000                    8             9   
7                      7            28000                    6             7   
8                      8            30000                    5             6   
9                      9            32000                    4             5   
10                     1            11000                    2             3   
11                     2            13000                    3             4   
12                     3            16000                    4             5   
13                     4            19000                    5             6   
14                     5            21000                    6             7   
15                     6            23000                    7             8   
16                     7            26000                    8             9   
17                     8            29000                    6             7   
18                     9            31000                    5             6   
19                    10            34000                    4             5   

    ml_skill  final_salary  
0          2         21200  
1          3         28600  
2          4         36000  
3          5         43400  
4          6         50800  
5          7         58200  
6          8         66600  
7          7         68200  
8          6         69000  
9          5         69800  
10         3         23600  
11         4         31000  
12         5         38400  
13         6         45800  
14         7         53200  
15         8         60600  
16         9         69000  
17         8         72000  
18         7         72800  
19         6         73600

In [4]:
df
x = df.drop('final_salary', axis = 1)
y = df['final_salary']

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=10)

In [6]:
lin_reg_model = LinearRegression()
lin_reg_model.fit(x_train, y_train)

LinearRegression()

In [7]:
lin_reg_model.coef_

array([  22.33310912,    1.91197304,  646.7191511 ,  646.7191511 ,
       1331.29298393])

In [8]:
lin_reg_model.intercept_

np.float64(-4061.093112962779)

In [9]:
y_pred_test = lin_reg_model.predict(x_test)

In [10]:
y_test

7     68200
10    23600
5     58200
6     66600
Name: final_salary, dtype: int64

In [11]:
y_pred_test[:5]

array([67356.88360536, 24220.41813664, 57133.81745302, 65516.80096641])

In [12]:
y_pred_test = lin_reg_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred_test)
print("MSE :",mse)
rmse = np.sqrt(mse)
print("RMSE :", rmse)
mae = mean_absolute_error(y_test, y_pred_test)
print("MAE :",mae)
r2_value = r2_score(y_test, y_pred_test)
print("R-squared :",r2_value)

MSE : 851457.3222598559
RMSE : 922.7444512213855
MAE : 903.2290279627268
R-squared : 0.9973843766739834


In [13]:
y_pred_train = lin_reg_model.predict(x_train)
mse = mean_squared_error(y_train, y_pred_train)
print("MSE :",mse)
rmse = np.sqrt(mse)
print("RMSE :", rmse)
mae = mean_absolute_error(y_train, y_pred_train)
print("MAE :",mae)
r2_value = r2_score(y_train, y_pred_train)
print("R-squared :",r2_value)

MSE : 682692.0635029564
RMSE : 826.2518160361019
MAE : 653.6952448281993
R-squared : 0.9977056223710201


In [35]:
BASE_DIR = os.path.dirname(os.path.abspath(r"E:\salary prediction\data"))
MODEL_PATH = os.path.join(BASE_DIR, "salary_model.pkl")
joblib.dump(lin_reg_model, MODEL_PATH)

['E:\\salary prediction\\salary_model.pkl']

In [22]:
job_experience_years = 10
previous_salary = 85000
study_hours_per_day = 8
python_skill = 7
ml_skill = 6

# Create test array
test_array = np.zeros((1,5))

test_array[0,0] = job_experience_years
test_array[0,1] = previous_salary
test_array[0,2] = study_hours_per_day
test_array[0,3] = python_skill
test_array[0,4] = ml_skill

print(test_array)

[[1.0e+01 8.5e+04 8.0e+00 7.0e+00 6.0e+00]]


In [23]:
predicted_salary = lin_reg_model .predict(test_array)[0]
print("Predicted Salary:", predicted_salary)

Predicted Salary: 176368.49149587494
